# Generated by Django 3.0 on 2020-06-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='fakturoid_invoice_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='fakturoid_public_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
