CREDIT_BALANCE_TOPUP = 'TOPUP'
# CREDIT_BALANCE_PAYMENT_RETURNED = 'PAYMENT_RETURNED'
CREDIT_BALANCE_COMMISSION = 'COMMISSION'
CREDIT_BALANCE_PATIENT_PAYCHECK = 'PATIENT_PAYCHECK'
CREDIT_BALANCE_BANK_TRANSFER_FEE = 'BANK_TRANSFER_FEE'
CREDIT_BALANCE_POST_OFFICE_FEE = 'POST_OFFICE_FEE'
CREDIT_BALANCE_TOPDOWN = 'TOPDOWN'

CREDIT_BALANCE_CHOICES = (
    (CREDIT_BALANCE_TOPUP, 'TOPUP'),
    (CREDIT_BALANCE_COMMISSION, 'COMMISSION'),
    (CREDIT_BALANCE_PATIENT_PAYCHECK, 'PATIENT_PAYCHECK'),
    (CREDIT_BALANCE_BANK_TRANSFER_FEE, 'BANK_TRANSFER_FEE'),
    (CREDIT_BALANCE_POST_OFFICE_FEE, 'POST_OFFICE_FEE'),
    (CREDIT_BALANCE_TOPDOWN, 'TOPDOWN')
)
