---
dependencies: []

galaxy_info:
  author: Tobias Schifftner
  description: Installs exim4 (sendonly) on Debian/Ubuntu linux servers.
  company: ambimax® GmbH
  license: MIT
  role_name: exim4_sendonly
  min_ansible_version: 2.5
  platforms:
  - name: Debian
    versions:
    - jessie
    - stretch
  - name: Ubuntu
    versions:
    - xenial
    - bionic
  galaxy_tags:
    - debian
    - ubuntu
    - exim4
    - sendonly