PAYMENT_TYPE_CONSTANT_PAYCHECK_BANK_TRANSFER = 600
PAYMENT_TYPE_CONSTANT_FEE_BANK_TRANSFER = 700
PAYMENT_TYPE_CONSTANT_COMMISSION = 800
PAYMENT_TYPE_CONSTANT_PAYCHECK_POST_OFFICE = 610
PAYMENT_TYPE_CONSTANT_FEE_POST_OFFICE = 710
# PAYMENT_TYPE_CONSTANT_PAYCHECK_COMMISSION = 810
PAYMENT_TYPE_CONSTANT_PAYCHECK_TOPDOWN = 999  # vrácení platby

PAYMENT_TYPE_CONSTANT_SYMBOL_CHOICES = (
    (PAYMENT_TYPE_CONSTANT_PAYCHECK_BANK_TRANSFER, 'bank. převod na účet pacienta'),
    (PAYMENT_TYPE_CONSTANT_FEE_BANK_TRANSFER, 'poplatky za bank. převody'),
    (PAYMENT_TYPE_CONSTANT_COMMISSION, 'provize'),
    (PAYMENT_TYPE_CONSTANT_PAYCHECK_POST_OFFICE, 'převod na účet ČP'),
    (PAYMENT_TYPE_CONSTANT_FEE_POST_OFFICE, 'poplatky za ČP'),
    (PAYMENT_TYPE_CONSTANT_PAYCHECK_TOPDOWN, 'přeplatek studie'),
)
