# Generated by Django 3.0 on 2020-05-18 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '0029_auto_20200507_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upraveno')),
                ('total_value', models.PositiveIntegerField()),
                ('url', models.URLField(blank=True, null=True)),
                ('variable_symbol', models.CharField(max_length=255)),
                ('specific_symbol', models.CharField(max_length=255)),
                ('constant_symbol', models.PositiveSmallIntegerField(choices=[(600, 'bank. převod na účet pacienta'), (700, 'poplatky za bank. převody'), (800, 'provize'), (610, 'převod na účet ČP'), (710, 'poplatky za ČP'), (999, 'přeplatek studie')])),
                ('bank_account_from', models.CharField(max_length=255)),
                ('bank_account_to', models.CharField(max_length=255)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='studies.Study')),
            ],
            options={
                'verbose_name': 'Money order',
                'verbose_name_plural': 'Money orders',
            },
        ),
    ]
