# Generated by Django 3.0 on 2020-05-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='returned_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='vráceno'),
        ),
    ]
