# Generated by Django 3.0 on 2020-06-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20200525_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sent_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='odesláno'),
        ),
    ]
