# Generated by Django 3.0 on 2020-06-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_sent_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='specific_symbol',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
