# Generated by Django 3.0 on 2020-06-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20200602_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoiced_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fakturováno'),
        ),
    ]
