# Generated by Django 3.0 on 2020-06-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_invoiced_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='item_value',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='vat_rate',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='vat_value',
            field=models.BigIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_value',
            field=models.BigIntegerField(blank=True),
        ),
    ]
