# Generated by Django 3.0 on 2020-06-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20200604_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='resent_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='znovu odesláno'),
        ),
    ]
