# Generated by Django 3.0 on 2020-06-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_payment_resent_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='constant_symbol',
            field=models.IntegerField(choices=[(600, 'bank. převod na účet pacienta'), (700, 'poplatky za bank. převody'), (800, 'provize'), (610, 'převod na účet ČP'), (710, 'poplatky za ČP'), (999, 'přeplatek studie')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='specific_symbol',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='variable_symbol',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
