# Generated by Django 3.0 on 2020-08-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_auto_20200722_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='invoiced_on',
        ),
    ]
