# Generated by Django 3.0 on 2020-09-09 11:04

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_auto_20200907_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='city',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='payment',
            name='name',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='payment',
            name='street',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='street'),
        ),
        migrations.AddField(
            model_name='payment',
            name='street_number',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='street_number'),
        ),
        migrations.AddField(
            model_name='payment',
            name='zip',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='zip'),
        ),
    ]
