# Generated by Django 3.0 on 2020-04-24 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revisions', '0002_auditlog_group_obj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='group_obj',
            new_name='study',
        ),
    ]
