# Generated by Django 3.0 on 2020-03-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('ADMIN', 'CRA')], max_length=255, null=True, verbose_name='role'),
        ),
    ]
