# Generated by Django 3.0 on 2020-03-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('CRA', 'CRA')], max_length=255, null=True, verbose_name='role'),
        ),
    ]
