galaxy_info:
  role_name: endevel-server
  author: Lubos Truhlar
  description: role for setup the server
  company: Endevel s.r.o.

  license: license (GPLv2, CC-BY, etc)

  min_ansible_version: 2.7

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  # Optionally specify the branch Galaxy will use when accessing the GitHub
  # repo for this role. During role install, if no tags are available,
  # Galaxy will use this branch. During import Galaxy will access files on
  # this branch. If Travis integration is configured, only notifications for this
  # branch will be accepted. Otherwise, in all cases, the repo's default branch
  # (usually master) will be used.
  #github_branch:

  #
  # Provide a list of supported platforms, and for each platform a list of versions.
  # If you don't wish to enumerate all versions for a particular platform, use 'all'.
  # To view available platforms and versions (or releases), visit:
  # https://galaxy.ansible.com/api/v1/platforms/
  #
  platforms:
  - name: Debian
    versions:
    - 8
    - 9

  galaxy_tags: []
    # List tags for your role here, one per line. A tag is a keyword that describes
    # and categorizes the role. Users find roles by searching for tags. Be sure to
    # remove the '[]' above, if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
    #       Maximum 20 tags per role.


dependencies:
    - role: weareinteractive.sudo
      version: 1.12.2
      vars:
        sudo_users:
          - name: "{{ user }}"
            nopasswd: yes
        sudo_defaults:
          - defaults: env_keep += "SSH_AUTH_SOCK"
    - role: willshersystems.sshd
      version: v0.7.4
      vars:
        sshd:
          AllowAgentForwarding: yes
          PermitRootLogin: without-password
          PasswordAuthentication: no
    - role: geerlingguy.nginx
      version: 2.6.2
      vars:
        nginx_conf_template: nginx.conf.j2
        nginx_server_names_hash_bucket_size: 128
    - role: geerlingguy.git
      version: 2.0.4
    - role: geerlingguy.postgresql
      version: 1.4.5
      vars:
        postgresql_hba_entries:
          - { type: local, database: all, user: postgres, auth_method: peer }
          - { type: local, database: all, user: all, auth_method: peer }
          - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5 }
          - { type: host, database: all, user: all, address: '::1/128', auth_method: md5 }
        postgresql_locales:
          - 'cs_CZ.UTF-8'
          - 'en_US.UTF-8'
        postgresql_users:
          - name: "{{ db_superuser }}"
            password: "{{ vault_database_password }}"
            role_attr_flags: SUPERUSER
    - role: geerlingguy.pip
      version: 1.3.0
    - role: geerlingguy.supervisor
      version: 2.0.2
      vars:
        supervisor_unix_http_server_enable: false
        supervisor_unix_http_server_password_protect: false
        supervisor_inet_http_server_enable: True
        supervisor_inet_http_server_port: 8080
        supervisor_inet_http_server_password_protect: false
    - role: tschifftner.exim4_sendonly
      vars:
        exim4_sendonly_email_addresses:
          root: 'noreply@endevel.cz'
    - role: weareinteractive.ufw
      version: 1.9.0
      vars:
        ufw_rules: [{ port: 22, rule: allow }, { port: 80, rule: allow }, { port: 443, rule: allow }]
    - role: geerlingguy.nodejs
      version: 5.0.0
    - role: geerlingguy.redis
      vars:
        redis_unixsocket: '/var/run/redis/redis.sock'
    - role: oefenweb.fail2ban
      version: v3.3.3
      vars:
        fail2ban_sendername: 'noreply@endevel.cz'
        fail2ban_ignoreips:
          - 90.177.99.144
          - 127.0.0.1/8
        fail2ban_maxretry: 5
        fail2ban_destemail: support@endevel.cz
        fail2ban_mta: exim4
    - src: lafranceinsoumise.backup
      version: 4.2.1
      vars:
        backup_user: "{{ user }}"
        backup_profiles:
          # Backup file path
          - name: ansible                         # Required params
            schedule: 03 00 * * *                       # At 3am every day
            source: /mnt/backup/
            # target: "s3://backup-endevel.s3.eu-central-1.amazonaws.com/{{ inventory_hostname }}/"
            target: "ftp://endevel_backup:{{ vault_ftp_backup_password }}@mail.eupolymer.cz/{{ inventory_hostname }}/"
    - src: git+git@github.com:EndevelCZ/ansible-python.git
      version: v0.0.4
      when: python_compile
