- name: reload nginx
  become: yes
  become_user: root
  service:
    name: nginx
    state: reloaded

- name: restart supervisor
  supervisorctl:
    name: "{{ project_name }}"
    state: restarted

- name: restart supervisor vue
  supervisorctl:
    name: "{{ vue_project_name }}"
    state: restarted
  when:
  - not vue_frontend_static
  - vue_frontend

- name: restart celery via supervisor
  supervisorctl:
    name: "{{ project_name }}_celery"
    state: restarted
  listen: "restart celery"
  when: celery_enabled
