---

- name: "Creating sudoers configuration in /etc/sudoers.d/{{ sudo_sudoers_file }}"
  template:
    src: "etc/sudoers.d/ansible.j2"
    dest: "/etc/sudoers.d/{{ sudo_sudoers_file }}"
    validate: "visudo -cf %s"
    owner: root
    group: "{{ sudo_sudoers_group }}"
    mode: "0440"

- name: List files in /etc/sudoers.d
  find:
    paths: /etc/sudoers.d
    patterns: "*"
  register: sudoers_contents
  changed_when: false
  when: purge_other_sudoers_files

- name: Remove unmanaged /etc/sudoers.d/ files
  file:
    path: "/etc/sudoers.d/{{ item.path|basename }}"
    state: absent
  loop: "{{ sudoers_contents.files }}"
  loop_control:
    label: "{{ item.path }}"
  when:
    - purge_other_sudoers_files
    - (item.path|basename) != sudo_sudoers_file

...