---

- import_tasks: vars.yml
  tags:
    - system
    - sudo
    - vars
    - sudo-vars

- import_tasks: install.yml
  tags:
    - system
    - sudo
    - install
    - sudo-install

- import_tasks: config.yml
  tags:
    - system
    - sudo
    - config
    - sudo-config
