# Generated by Django 3.0 on 2020-03-17 20:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import main.apps.companies.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upraveno')),
                ('name', models.CharField(db_index=True, max_length=512, verbose_name='obchodní název')),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.apps.companies.utils.company_dir_path, verbose_name='obrázek')),
                ('description', models.TextField(blank=True, null=True, verbose_name='popis')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='data')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='telefon')),
                ('web', models.URLField(blank=True, null=True, verbose_name='web')),
                ('reg_number', models.CharField(blank=True, max_length=32, null=True, verbose_name='IČ')),
                ('vat_number', models.CharField(blank=True, max_length=32, null=True, verbose_name='DIČ')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='ulice')),
                ('street_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='čp')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='město')),
                ('zip', models.CharField(blank=True, max_length=255, null=True, verbose_name='PSČ')),
                ('gps_lat', models.CharField(blank=True, max_length=32, null=True, verbose_name='GPS lat')),
                ('gps_lng', models.CharField(blank=True, max_length=32, null=True, verbose_name='GPS lng')),
            ],
            options={
                'verbose_name': 'obchodní subjekt',
                'verbose_name_plural': 'obchodní subjekty',
            },
        ),
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upraveno')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_company', to='companies.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
