# Generated by Django 3.0 on 2020-03-19 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20200317_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='owners',
            new_name='users',
        ),
    ]
