# Generated by Django 3.0 on 2020-03-29 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20200321_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='gps_lat',
        ),
        migrations.RemoveField(
            model_name='company',
            name='gps_lng',
        ),
    ]
