# Generated by Django 3.0 on 2020-06-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20200329_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='fa_subject_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='subject_id'),
        ),
    ]
