# Generated by Django 3.0 on 2020-07-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20200707_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='commission',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
