# Generated by Django 2.0 on 2019-05-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiobankTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=15, verbose_name='ID Transakce')),
                ('date', models.DateField(verbose_name='Datum pohybu')),
                ('amount', models.FloatField(verbose_name='Částka')),
                ('currency', models.CharField(max_length=3, verbose_name='Měna')),
                ('account_number', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=255)),
                ('bank_code', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=60)),
                ('constant_symbol', models.CharField(max_length=4)),
                ('variable_symbol', models.CharField(max_length=10)),
                ('specific_symbol', models.CharField(max_length=10)),
                ('user_identification', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=140)),
                ('instruction_id', models.CharField(max_length=12)),
                ('bic', models.CharField(max_length=11)),
                ('recipient_message', models.CharField(max_length=140)),
            ],
            options={
                'verbose_name': 'FioBank Transakce',
                'verbose_name_plural': 'FioBank Transakce',
            },
        ),
    ]
