# Generated by Django 2.0 on 2019-05-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiobanka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiobanktransactions',
            name='account_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fiobanktransactions',
            name='account_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fiobanktransactions',
            name='bank_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fiobanktransactions',
            name='bank_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='fiobanktransactions',
            name='bic',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='fiobanktransactions',
            name='comment',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='fiobanktransactions',
            name='constant_symbol',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='fiobanktransactions',
            name='instruction_id',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='fiobanktransactions',
            name='recipient_message',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='fiobanktransactions',
            name='specific_symbol',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fiobanktransactions',
            name='user_identification',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fiobanktransactions',
            name='variable_symbol',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
