# Generated by Django 2.0 on 2019-05-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiobanka', '0002_auto_20190515_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiobanktransactions',
            name='bank_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
