# Generated by Django 3.0 on 2020-03-22 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upraveno')),
                ('status', models.CharField(choices=[('DRAFT', 'draft'), ('PRELAUNCH', 'prelaunch'), ('PROGRESS', 'progress'), ('BILLING', 'billing'), ('CLOSED', 'closed')], max_length=64, verbose_name='status')),
                ('number', models.PositiveIntegerField(verbose_name='study number')),
                ('identifier', models.CharField(max_length=255, verbose_name='study identifier')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('bank_transfer', models.BooleanField(default=False, verbose_name='bank transfer')),
                ('post_office_cash', models.BooleanField(default=False, verbose_name='czech Post payment order (cash)')),
                ('pay_frequency', models.PositiveSmallIntegerField(default=1, verbose_name='monthly pay frequency')),
            ],
            options={
                'verbose_name': 'study',
                'verbose_name_plural': 'studies',
            },
        ),
        migrations.CreateModel(
            name='StudyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_users', to='studies.Study')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='study',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='studies', through='studies.StudyUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
