# Generated by Django 3.0 on 2020-03-29 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_study_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'draft'), ('PRELAUNCH', 'prelaunch'), ('PROGRESS', 'progress'), ('BILLING', 'billing'), ('CLOSED', 'closed')], default='DRAFT', max_length=64, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='StudyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upraveno')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.CharField(max_length=2048, verbose_name='local language title')),
                ('price', models.IntegerField(verbose_name='value')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_items', to='studies.Study', verbose_name='study')),
            ],
            options={
                'verbose_name': 'study item',
                'verbose_name_plural': 'study items',
            },
        ),
    ]
