# Generated by Django 3.0 on 2020-03-29 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_auto_20200329_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upraveno')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('max_unsheduled', models.IntegerField(default=0, verbose_name='value')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arms', to='studies.Study', verbose_name='study')),
            ],
            options={
                'verbose_name': 'arm',
                'verbose_name_plural': 'arms',
            },
        ),
    ]
