# Generated by Django 3.0 on 2020-03-29 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studies', '0004_arm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upraveno')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('expected_patients', models.IntegerField(default=0, verbose_name='Exp. patients')),
                ('pin', models.CharField(max_length=16, verbose_name='pin')),
                ('cra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to=settings.AUTH_USER_MODEL, verbose_name='cra')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='studies.Study', verbose_name='study')),
            ],
            options={
                'verbose_name': 'site',
                'verbose_name_plural': 'sites',
            },
        ),
    ]
