# Generated by Django 3.0 on 2020-03-29 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0005_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arm',
            old_name='max_unsheduled',
            new_name='max_unscheduled',
        ),
    ]
