# Generated by Django 3.0 on 2020-03-29 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0007_historicalarm_historicalsite_historicalstudy_historicalstudyitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalarm',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historicalarm',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalsite',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historicalsite',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalstudy',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historicalstudy',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalstudyitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historicalstudyitem',
            name='updated_at',
        ),
    ]
