# Generated by Django 3.0 on 2020-04-07 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0009_historicalpatient_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='status',
            field=models.CharField(choices=[('TERMINDATED', 'terminated'), ('ACTIVE', 'active')], default='ACTIVE', max_length=64, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='street'),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='zip',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='zip'),
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('TERMINDATED', 'terminated'), ('ACTIVE', 'active')], default='ACTIVE', max_length=64, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='patient',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='street'),
        ),
        migrations.AddField(
            model_name='patient',
            name='zip',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='zip'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='number',
            field=models.CharField(max_length=255, verbose_name='randomisation'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='payment_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='payment info'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='number',
            field=models.CharField(max_length=255, verbose_name='randomisation'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='payment_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='payment info'),
        ),
        migrations.CreateModel(
            name='PatientPaymentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upraveno')),
                ('payment_type', models.CharField(choices=[('BANK', 'bank transfer'), ('POST', 'czech Post payment order (cash)')], max_length=32, verbose_name='payment form')),
                ('payment_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='payment info')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='street')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='city')),
                ('zip', models.CharField(blank=True, max_length=255, null=True, verbose_name='zip')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_data', to='studies.Patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
