# Generated by Django 3.0 on 2020-04-08 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0010_auto_20200407_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='studies.Site', verbose_name='site'),
        ),
        migrations.AddField(
            model_name='patient',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='studies.Site', verbose_name='site'),
            preserve_default=False,
        ),
    ]
