# Generated by Django 3.0 on 2020-04-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0012_historicalvisit_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvisit',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
        migrations.AddField(
            model_name='visit',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
    ]
