# Generated by Django 3.0 on 2020-04-08 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0014_historicalvisititem_visititem'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvisititem',
            name='study_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='studies.StudyItem', verbose_name='study item'),
        ),
        migrations.AddField(
            model_name='visititem',
            name='study_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='visit_items', to='studies.StudyItem', verbose_name='study item'),
            preserve_default=False,
        ),
    ]
