# Generated by Django 3.0 on 2020-04-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0017_auto_20200410_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientvisititem',
            options={'verbose_name': 'patient visit item', 'verbose_name_plural': 'patient visit items'},
        ),
        migrations.AddField(
            model_name='patientvisititem',
            name='approved',
            field=models.NullBooleanField(default=None, verbose_name='approved'),
        ),
        migrations.AddField(
            model_name='patientvisititem',
            name='note_cra',
            field=models.TextField(blank=True, null=True, verbose_name='note cra'),
        ),
        migrations.AddField(
            model_name='patientvisititem',
            name='origin',
            field=models.CharField(choices=[('CRA', 'CRA'), ('SITE', 'SITE')], default='SITE', max_length=64, verbose_name='origin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientvisititem',
            name='reject_reason',
            field=models.TextField(blank=True, null=True, verbose_name='reject reason'),
        ),
    ]
