# Generated by Django 3.0 on 2020-04-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0018_auto_20200417_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudy',
            name='number',
            field=models.CharField(max_length=255, verbose_name='study number'),
        ),
        migrations.AlterField(
            model_name='patientvisititem',
            name='origin',
            field=models.CharField(choices=[('CRA', 'CRA'), ('SITE', 'SITE')], default='CRA', max_length=64, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='study',
            name='number',
            field=models.CharField(max_length=255, verbose_name='study number'),
        ),
    ]
