# Generated by Django 3.0 on 2020-04-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0023_auto_20200425_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvisit',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='order'),
        ),
    ]
