# Generated by Django 3.0 on 2020-05-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0026_auto_20200505_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudy',
            name='variable_symbol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='variable_symbol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
