# Generated by Django 3.0 on 2020-05-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0027_auto_20200505_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisititem',
            name='payment_status',
            field=models.CharField(choices=[('WAITING', 'WAITING'), ('SENT', 'SENT'), ('RETURNED', 'RETURNED')], max_length=32, null=True),
        ),
    ]
