# Generated by Django 3.0 on 2020-05-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0028_patientvisititem_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstudy',
            name='variable_symbol',
        ),
        migrations.AddField(
            model_name='study',
            name='commission',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='historicalvisit',
            name='number',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='max unscheduled'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='number',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='max unscheduled'),
        ),
    ]
