# Generated by Django 3.0 on 2020-05-25 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0029_auto_20200507_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvisit',
            name='notify_cra',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='notify_cra',
        ),
    ]
