# Generated by Django 3.0 on 2020-06-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0033_auto_20200616_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='arm',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalarm',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
