# Generated by Django 3.0 on 2020-06-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0034_auto_20200618_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalsite',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
