# Generated by Django 3.0 on 2020-07-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0035_auto_20200623_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='users',
        ),
        migrations.AlterField(
            model_name='historicalstudy',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='study',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='notes'),
        ),
        migrations.DeleteModel(
            name='StudyUser',
        ),
    ]
