# Generated by Django 3.0 on 2020-07-14 15:19

from django.db import migrations, models
import main.apps.studies.models.sites


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0036_auto_20200714_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsite',
            name='contract_path',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='contract_path',
            field=models.FileField(blank=True, null=True, upload_to=main.apps.studies.models.sites.get_contract_path),
        ),
    ]
