# Generated by Django 3.0 on 2020-07-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0037_auto_20200714_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='variable_symbol',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
