# Generated by Django 3.0 on 2020-07-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0038_auto_20200720_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvisititem',
            name='payment_status',
            field=models.CharField(choices=[('WAITING', 'WAITING'), ('SENT', 'SENT'), ('RETURNED', 'RETURNED')], default='WAITING', max_length=32, null=True),
        ),
    ]
