# Generated by Django 3.0 on 2020-08-23 14:52

from django.db import migrations, models
import main.apps.studies.models.sites


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0040_auto_20200803_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsite',
            name='site_instructions_path',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='site_instructions_path',
            field=models.FileField(blank=True, null=True, upload_to=main.apps.studies.models.sites.get_contract_path),
        ),
    ]
