# Generated by Django 3.0 on 2020-08-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0041_auto_20200823_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='arm',
            name='d_visit_items_cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
