# Generated by Django 3.0 on 2020-09-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0043_auto_20200902_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisit',
            name='d_reim_approved',
            field=models.BooleanField(default=False),
        ),
    ]
