# Generated by Django 3.0 on 2020-09-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0044_patientvisit_d_reim_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudy',
            name='bank_account',
            field=models.CharField(help_text='bankovní účet pro vrácení přeplatku studie', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='bank_account',
            field=models.CharField(help_text='bankovní účet pro vrácení přeplatku studie', max_length=64, null=True),
        ),
    ]
