# Generated by Django 3.0 on 2020-09-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0045_auto_20200911_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsite',
            name='contract_path',
        ),
        migrations.RemoveField(
            model_name='historicalsite',
            name='site_instructions_path',
        ),
        migrations.RemoveField(
            model_name='site',
            name='contract_path',
        ),
        migrations.RemoveField(
            model_name='site',
            name='site_instructions_path',
        ),
        migrations.AlterField(
            model_name='historicalstudy',
            name='operator',
            field=models.CharField(choices=[('CRO', 'CRO'), ('SPONSOR', 'SPONSOR')], default='SPONSOR', max_length=32, verbose_name='study operator'),
        ),
        migrations.AlterField(
            model_name='study',
            name='operator',
            field=models.CharField(choices=[('CRO', 'CRO'), ('SPONSOR', 'SPONSOR')], default='SPONSOR', max_length=32, verbose_name='study operator'),
        ),
    ]
