"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 1.11.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import logging
import os
import sys

from decouple import AutoConfig, Csv  # instance settings
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _

config = AutoConfig(os.environ.get('DJANGO_CONFIG_ENV_DIR'))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('PROJECT_SECRET_KEY', default='')

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(PROJECT_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

DEBUG = False
DEBUG_TOOLBAR = False
ALLOW_ROBOTS = True

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
BASE_PROTOCOL = config('BASE_PROTOCOL', default='http') + "://"
BASE_URL = BASE_PROTOCOL + config('PROJECT_MAIN_DOMAIN', default='')
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='', cast=lambda v: [s.strip() for s in v.split(',')])

ADMINS = []
MANAGERS = ADMINS


EMAIL_HOST = config('EMAIL_HOST', default='localhost')
EMAIL_PORT = config('EMAIL_PORT', default=25, cast=int)
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=False, cast=bool)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='vypln email v env')
DEFAULT_NOTIFICATION_EMAIL = config('DEFAULT_NOTIFICATION_EMAIL', default=DEFAULT_FROM_EMAIL)
EMAIL_SUBJECT_PREFIX = ''
SERVER_EMAIL = 'info@endevel.cz'         # The email address that error messages come from
SEND_BROKEN_LINK_EMAILS = False

UPLOADED_ATTACHMENTS_DIR = u'/tmp/'

# Application definition

INSTALLED_APPS = [
    'main.libraries',
    'main.apps.users',
    'main.apps.companies',
    'main.apps.studies',
    'main.apps.revisions',
    'main.apps.fiobanka',
    'main.apps.core',
    'main.apps.credit',
    'main.apps.payments',
    'main.apps.topups',
    'main.apps.invoices',
    'main.apps.ticket',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.messages',
    'django.contrib.postgres',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.staticfiles',
    'django_cron',
    'django_extensions',
    'wkhtmltopdf',
    'encrypted_fields',

    'raven.contrib.django.raven_compat',
    'constance',
    'constance.backends.database',

    'rest_framework',
    'rest_framework.authtoken',
    'rest_auth',
    'django_filters',
    'allauth',
    'allauth.account',
    # 'allauth.socialaccount',    # providers added in by SOCIALACCOUNT_ENABLED
    'rest_auth.registration',
    'mptt',
    # 'sorl.thumbnail',
    'drf_yasg',
    'simple_history',
]

MIDDLEWARE = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

AUTHENTICATION_BACKENDS = (
    'allauth.account.auth_backends.AuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
)

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(PROJECT_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'


# local DB
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('POSTGRESQL_DATABASE', default=''),
        'USER': config('POSTGRESQL_USER', default=''),
        'HOST': config('POSTGRESQL_HOST', default=''),
        'PORT': config('POSTGRESQL_PORT', default=''),
        'PASSWORD': config('POSTGRESQL_PASSWORD', default=''),
        'ATOMIC_REQUESTS': True,
        'CONN_MAX_AGE': 600,
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'cs'

TIME_ZONE = 'Europe/Prague'

USE_I18N = True

USE_L10N = True

USE_TZ = False  # do not use, if not creating multi TZ application

LANGUAGES = (
    ('cs', _('Czech')),
)

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

STATICFILES_DIRS = [
    os.path.join(PROJECT_DIR, 'static'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'collected-static')
STATIC_URL = '/collected-static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Login settings

SITE_ID = 1

# allauth settings
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_DEFAULT_HTTP_PROTOCOL = BASE_PROTOCOL
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_SESSION_REMEMBER = False
# ACCOUNT_SIGNUP_FORM_CLASS = 'main.libraries.forms.SignupForm'
AUTH_USER_MODEL = 'users.User'
ACCOUNT_ADAPTER = 'main.libraries.adapters.CustomDefaultAccountAdapter'
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = False
# ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = LOGIN_REDIRECT_URL
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = reverse_lazy('login')
ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = False

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'main.libraries.pagination.CustomPageNumberPagination',
    'DEFAULT_FILTER_BACKENDS': ['main.libraries.filters.CustomDjangoFilterBackend'],
    'PAGE_SIZE': 20,
    'SEARCH_PARAM': 'q',
}
REST_AUTH_SERIALIZERS = {
    'USER_DETAILS_SERIALIZER': 'main.apps.users.serializers.UserSerializer',
    'PASSWORD_RESET_SERIALIZER': 'main.apps.users.serializers.CustomPasswordResetSerializer',
}


LOGIN_REDIRECT_URL = "/"

SOCIAL_ACCOUNTS_ENABLED = False

CRON_CLASSES = [
    'main.apps.fiobanka.cron.FioBankPairingPayments',
    'main.apps.core.cron.FioBankProcessingPayments',
    'main.apps.payments.cron.GeneratingPayments',
    'main.apps.credit.cron.GenerateCommissions',
    'main.apps.invoices.cron.GenerateInvoices',
    # 'django_cron.cron.FailedRunsNotificationCronJob'
    'main.apps.ticket.cron.SendTicketsCronJob',
    'main.apps.core.cron.StudyCloseCron',
]

DJANGO_CRON_DELETE_LOGS_OLDER_THAN = 7

# Constance
CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'  # this is needed if Redis is not used
CONSTANCE_CONFIG = {
    'FIO_BANK_TOKEN': ('', 'token pro FIO Banku kreditního účtu'),
    'FIO_BANK_TOKEN_OPERATIONAL': ('', 'token pro FIO Banku operačního účtu'),
    'BANK_ACCOUNT_CREDIT': ('', 'číslo kreditního účtu'),
    'BANK_ACCOUNT_OPERATIONAL': ('', 'číslo provozního účtu'),
    'BANK_TRANSFER_FEE': (0, 'poplatek za bankovní převod (zadávejte v haléřích vč. DPH)', int),
    'POST_OFFICE_INVOICE_FEE': (6000, 'poplatek za poštovní poukázku to co se fakturuje (zadávejte v haléřích vč. DPH)', int),
    'POST_OFFICE_FEE': (4300, 'poplatek za poštovní poukázku pro platby do 5000,- (zadávejte v haléřích vč. DPH)', int),
    'POST_OFFICE_FEE_2': (5300, 'poplatek za poštovní poukázku pro platby nad 5000,- (zadávejte v haléřích vč. DPH)', int),
    'POST_OFFICE_BANK_ACCOUNT': ('', 'číslo účtu ČP'),
    'POST_OFFICE_SENDER_NUMBER': ('', 'číslo odesílatele, které vám přidělali ČP'),
    'PAYMENT_GENERATION_DAY': (15, 'den v měsíci kdy se budou generovat platební příkazy', int),
    'FAKTUROID_SLUG': ('', 'FAKTUROID SLUG'),
    'FAKTUROID_EMAIL': ('', 'FAKTUROID_EMAIL'),
    'FAKTUROID_API_KEY': ('', 'FAKTUROID_API_KEY'),
    'VAT_RATE': (0, 'výše DPH v procentech', int),
    'MIN_CREDIT_FOR_LAUNCH': (5000, 'minimální výše kreditu pro launch studie', int),
}


###################
# Redis and cache #
###################


PATH_TO_LOGDIR = os.path.join(config('PROJECT_HOME_DIR', ''), 'log/')
os.makedirs(PATH_TO_LOGDIR, exist_ok=True)
DEBUG_LOG_FILE = os.path.join(PATH_TO_LOGDIR, 'debug.log')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d'
                      '%(thread)d <%(name)s|%(filename)s:%(lineno)s> %(message)s'
        },
        'plain': {
            'format': '%(asctime)s %(levelname)s <%(name)s> %(message)s'
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.WatchedFileHandler',
            'filename': DEBUG_LOG_FILE,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'plain',
        },
    },
    'loggers': {
        'main': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG'
        },
        '': {
            'handlers': ['console', 'file', ],  #
            'level': 'ERROR',
            'propagate': True,
        },
    },
}

SHELL = "shell" in sys.argv or "shell_plus" in sys.argv

RAVEN_CONFIG = {
    'dsn': config('SENTRY_DSN', default=''),
    # If you are using git, you can also automatically configure the
    # release based on the git info.
    # 'release': raven.fetch_git_sha(BASE_DIR),
    'environment': config('ENVIRONMENT', default=''),
    'CELERY_LOGLEVEL': logging.INFO,
    "ignore_exceptions": ("*", ) if SHELL else ()
}

###################
# Redis and cache #
###################

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    },
}

CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_WHITELIST = (BASE_URL, )
CORS_URLS_REGEX = r'^/api/.*$'

MPTT_ADMIN_LEVEL_INDENT = 20

PHONENUMBER_DB_FORMAT = 'INTERNATIONAL'
PHONENUMBER_DEFAULT_REGION = 'CZ'

SMARTFORM_URL = 'https://secure.smartform.cz/smartform-ws/oracle/v6'
SMARTFORM_API_KEY = config('SMARTFORM_API_KEY', default='')

INT_RATIO = 1000 * 1000 * 1000

WKHTMLTOPDF_CMD = config('WKHTMLTOPDF_CMD', default='wkhtmltopdf')

FIELD_ENCRYPTION_KEYS = [
    config('FIELD_ENCRYPTION_KEY', default=''),
]

DOCTOR_SESSION_KEY = 'patients'
DOCTOR_SESSION_MIN = 30
