# Generated by Django 3.0 on 2020-05-21 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '0029_auto_20200507_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upraveno')),
                ('amount', models.PositiveIntegerField()),
                ('received', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topups', to='studies.Study')),
            ],
            options={
                'verbose_name': 'topup',
                'verbose_name_plural': 'topups',
            },
        ),
    ]
