# Generated by Django 3.0 on 2020-07-22 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topup',
            name='received',
        ),
    ]
