---
galaxy_info:
  author: Stanislav Bogatyrev <realloc@realloc.spb.ru>
  description: Generate Diffie-Hellman parameters file
  license: GPLv3
  min_ansible_version: 2.0.0
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty
    - name: Debian
      versions:
        - wheezy
        - jessie
    - name: opensuse
      versions:
        - 13.1
        - 13.2
  galaxy_tags:
    - system
    - ssl

dependencies: []
