- name: Create nginx virtual host for SSL
  become: yes
  become_method: sudo
  template:
    src: "{{ nxing_vhost_ssl_template | default('templates/nginx_vhost_ssl.j2') }}"
    dest: '/etc/nginx/sites-available/{{ project_name }}_ssl.conf'
  notify: reload nginx

- name: Create symlink to sites-enabled for SSL
  become: yes
  become_method: sudo
  file:
    dest: '/etc/nginx/sites-enabled/{{ project_name }}_ssl.conf'
    src: '/etc/nginx/sites-available/{{ project_name }}_ssl.conf'
    state: link
  notify: reload nginx


