# Generated by Django 3.0 on 2020-05-05 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '0027_auto_20200505_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upraveno')),
                ('balance_type', models.CharField(choices=[('TOPUP', 'TOPUP'), ('PAYMENT_RETURNED', 'PAYMENT_RETURNED'), ('COMMISSION', 'COMMISSION'), ('PATIENT_PAYCHECK', 'PATIENT_PAYCHECK')], max_length=32, verbose_name='typ pohybu')),
                ('balance_amount', models.FloatField(verbose_name='částka')),
                ('balance_sum', models.FloatField(verbose_name='sumarizace kreditu')),
                ('custom_fk_id', models.CharField(max_length=255, verbose_name='custom_fk_id')),
                ('reims', models.ManyToManyField(blank=True, to='studies.PatientVisitItem')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='studies.Study', verbose_name='study')),
            ],
            options={
                'verbose_name': 'credit balance',
                'verbose_name_plural': 'credit balances',
            },
        ),
    ]
