# Generated by Django 3.0 on 2020-05-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditbalance',
            name='balance_amount',
            field=models.IntegerField(verbose_name='částka'),
        ),
        migrations.AlterField(
            model_name='creditbalance',
            name='balance_sum',
            field=models.IntegerField(verbose_name='sumarizace kreditu'),
        ),
    ]
