# Generated by Django 3.0 on 2020-06-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0007_auto_20200604_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditbalance',
            name='balance_amount',
            field=models.BigIntegerField(blank=True, verbose_name='suma'),
        ),
        migrations.AlterField(
            model_name='creditbalance',
            name='balance_sum',
            field=models.BigIntegerField(blank=True, verbose_name='sumarizace kreditu'),
        ),
        migrations.AlterField(
            model_name='creditbalance',
            name='item_amount',
            field=models.BigIntegerField(verbose_name='bez DPH'),
        ),
        migrations.AlterField(
            model_name='creditbalance',
            name='vat_amount',
            field=models.BigIntegerField(blank=True, verbose_name='DPH'),
        ),
    ]
