# Generated by Django 3.0 on 2020-08-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0008_auto_20200604_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditbalance',
            name='invoiced_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fakturováno'),
        ),
    ]
